package com.practice.enums;

/**
 * Enums Learning & Demo
 * - Uses
 * 1. Enum enforces standards in coding
 * 2. Enum can be used in switch cases as well
 * 3. Enum extends a Enum class already 
 * 4. Enum can implement interfaces
 * 5. Enum doesn't have a public constructor hence can't be instantiated
 * 
 * This is the code automatically generated by compiler after declaring a enum class
 * protected Enum(String name, int ordinal) { 
 * 		this.name = name; this.ordinal = ordinal; 
 * }
 * And by default toString() is
 *  public String toString() {
 *      return name;
 *	} 
 * Comparing enum can be done with "==" as there is only one instance of enum created
 * @author Amrut
 *
 */
public class EnumsTutorial {

	public static void main(String[] args) {
		// Print all enum values
		for (DAYS day : DAYS.values()) {
			System.out.println(day.toString()); // print as String
			System.out.println(day.ordinal()); // print as associated indexes
		}
	}
}

enum DAYS {
	MON, TUE, WED, THU, FRI, SAT, SUN
}
